# Generated by Django 3.2.7 on 2021-10-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=40)),
                ('comuna', models.CharField(max_length=2)),
                ('barrio', models.CharField(max_length=20)),
                ('telofono', models.CharField(max_length=20)),
                ('fecharegistro', models.DateField()),
                ('fechafin', models.DateField()),
            ],
            options={
                'verbose_name': 'cali',
                'verbose_name_plural': 'cali',
            },
        ),
    ]
