# Generated by Django 3.2.9 on 2021-11-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='latitud',
            field=models.FloatField(default=1.0, verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamento',
            name='longitud',
            field=models.FloatField(default=1.0, verbose_name='Longitud'),
            preserve_default=False,
        ),
    ]
